remote_theme: jekyll/minima
title: Auton Lab
show_excerpts: true
url: /new_site_poc
baseurl: /new_site_poc
header_pages:
  - about.md
  - research_areas.md
  - broader_impact.md
  - publications.md
  - resources.md
  - people.md
  - careers.md
collections_dir: collections
collections:
  tutorials:
    output: true
    sort_by: complexity
  staff:
    output: true
    sort_by: last_name
