on:
  push:
    paths:
    - 'publications/*.bib'

jobs:
  update_pubs:
    runs-on: ubuntu-latest
    name: Update the bib publications
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publication Update Step
        uses: ./process_bibs/ # Uses an action in the root directory
        id: bibparse
