on:
  push:
    paths:
    - 'publications/*.bib'

jobs:
  update_pubs:
    runs-on: ubuntu-latest
    name: Update the bib publications
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publication Update Step
        uses: ./process_bibs/ # Uses an action in the root directory
        id: bibparse
      - name: Commit report
        run: |
          git config --global user.name 'Bibtex Parser'
          git config --global user.email 'bibtex@example.com'
          git commit -am "Automated push"
          git push